<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eggs</string>
		<string>eggshell</string>
	</array>
	<key>name</key>
	<string>Eggshell</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*!#.*</string>
			<key>name</key>
			<string>comment.line.source.eggshell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(pre|bq)\.</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.eggshell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>comment.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inlines</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(raw)\.</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.eggshell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>comment.eggshell</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.macro.eggshell</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.eggshell</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*@([\w!=]+)\s*(\{[^\s]*|)\s*$</string>
			<key>name</key>
			<string>support.macro.eggshell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*@([\w!=]+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.macro.eggshell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)\s*(\{[^\s]*|)\s*$</string>
			<key>name</key>
			<string>support.macro.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*[^\s]*\}$</string>
			<key>name</key>
			<string>support.function.macro.eggshell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^&lt;((script|style|div|blockquote|p|pre)[^&gt;]*)&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.eggshell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/(script|style|div|blockquote|p|pre)&gt;$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.eggshell</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.other.block.eggshell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([a-z0-9_-]+\.|[|\\/#&lt;&gt;*+-]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.eggshell</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.line.eggshell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>string.line.block.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-tick</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-brace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inlines</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>string.line.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-tick</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-brace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inlines</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>entity.source.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<key>attribute</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[ &lt;])([_a-zA-Z][\w:-]*)=</string>
			<key>end</key>
			<string>(?=['"&gt;])</string>
			<key>name</key>
			<string>entity.other.attribute-name.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quote-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quote-double</string>
				</dict>
			</array>
		</dict>
		<key>attribute-simple</key>
		<dict>
			<key>match</key>
			<string>\[a-zA-Z\]\[\\w-:\]+\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.simple.eggshell</string>
		</dict>
		<key>code-brace</key>
		<dict>
			<key>begin</key>
			<string>\{\{</string>
			<key>end</key>
			<string>\}\}</string>
			<key>name</key>
			<string>markup.raw.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>code-tick</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>markup.raw.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>html</key>
		<dict>
			<key>begin</key>
			<string>\&lt;[a-zA-Z_][\w:-]*</string>
			<key>end</key>
			<string>\&gt;</string>
			<key>name</key>
			<string>entity.name.tag.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-simple</string>
				</dict>
			</array>
		</dict>
		<key>html-end</key>
		<dict>
			<key>match</key>
			<string>&lt;/([a-zA-Z_][\w:]*)&gt;</string>
			<key>name</key>
			<string>entity.name.tag.eggshell</string>
		</dict>
		<key>inline-bold</key>
		<dict>
			<key>begin</key>
			<string>\[\*</string>
			<key>end</key>
			<string>\*\]</string>
			<key>name</key>
			<string>markup.bold</string>
		</dict>
		<key>inline-italic</key>
		<dict>
			<key>begin</key>
			<string>\[_</string>
			<key>end</key>
			<string>_\]</string>
			<key>name</key>
			<string>markup.italic</string>
		</dict>
		<key>inline-other</key>
		<dict>
			<key>begin</key>
			<string>\[-</string>
			<key>end</key>
			<string>-\]</string>
			<key>name</key>
			<string>markup.other</string>
		</dict>
		<key>inlines</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-other</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\$\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>support.function.interpol.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<key>map</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>entity.map.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#map-entry</string>
				</dict>
			</array>
		</dict>
		<key>map-entry</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[{,])('[^']*'|"[^"]*"|[\w_-]+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.map.eggshell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[,}])</string>
			<key>name</key>
			<string>constant.map.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>(-|\.)?[0-9]+(\.[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.eggshell</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>[+/*&lt;&gt;=%,-]+</string>
			<key>name</key>
			<string>support.operator.eggshell</string>
		</dict>
		<key>parameters</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.eggshell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quote-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quote-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#map</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-bad</string>
				</dict>
			</array>
		</dict>
		<key>quote-double</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>(?&lt;!\\)\"</string>
			<key>name</key>
			<string>string.quoted.double.eggshell</string>
		</dict>
		<key>quote-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>(?&lt;!\\)\'</string>
			<key>name</key>
			<string>string.quoted.single.eggshell</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9._\[\]]+</string>
			<key>name</key>
			<string>variable.source.eggshell</string>
		</dict>
		<key>variable-bad</key>
		<dict>
			<key>match</key>
			<string>\[^'\"\]?\w+[^\w]</string>
			<key>name</key>
			<string>invalid.source.eggshell</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>eggshell</string>
	<key>uuid</key>
	<string>7a823ca8-8c7f-472f-9d55-760b95a87532</string>
</dict>
</plist>
